import assert from 'node:assert/strict';
import C from '../catalog-core.js';
const base=()=>C.normalize({areas:[{name:'생활',color:'#aaaaaa'},{name:'건강',color:'#bbbbbb'}],activities:[{id:'meal',name:'식사',area:'생활',color:'#aabbcc'},{id:'walk',name:'산책',area:'건강',color:'#bbccdd'}],routineDefs:[{id:'r',actId:'meal',area:'생활'}]});
let serial=0;
const del=(s,kind,id,options={})=>C.deletion(s,C.preview(s,kind,id),{operationId:'op'+(++serial),at:123,...options});
let s=base();
const event={id:'e',actId:'meal',startTs:1000,endTs:601000,sessionIds:['s']};
const day={events:[event],todos:[{id:'t',title:'밥 먹기',actId:'meal',area:'생활',done:true}],routines:[{id:'r',actId:'meal',area:'생활',done:true}],todoMutations:[{id:'m',todo:{id:'t',actId:'meal',area:'생활'}}],statusMutations:[{id:'done'}]};
const eventsBefore=JSON.stringify(day.events);
s=del(s,'activity','meal').settings;
assert.equal(s.activities.length,1);
assert.equal(C.liveActivity(s,'meal'),undefined);
assert.equal(C.historicalActivity(s,'meal').name,'식사');
const clean=C.normalizeDay(s,day);
for(const item of [clean.todos[0],clean.routines[0],clean.todoMutations[0].todo]){
  assert.equal(item.actId,null);assert.equal(item.area,'생활');
  assert.equal(item.recordedClassification.actId,'meal');
}
assert.equal(clean.todos[0].done,true);assert.equal(JSON.stringify(clean.events),eventsBefore);
assert.deepEqual(clean.statusMutations,day.statusMutations);
assert.equal(s.routineDefs[0].actId,null);
s.areas[0].name='일상';s=C.normalize(s);
assert.equal(C.historicalActivity(s,'meal').area,'일상');
s=del(s,'area',s.areas[0].id).settings;
assert.equal(C.historicalActivity(s,'meal').area,'일상');
assert.equal(C.assignment(s,clean.todos[0]).area,null);
s.areas.push({id:'fresh-area',name:'일상'});s.activities.push({id:'breakfast',name:'식사',areaId:'fresh-area',area:'일상'});s=C.normalize(s);
assert.equal(C.assignment(s,clean.todos[0]).actId,null);
assert.notEqual(C.historicalActivity(s,'meal').areaId,C.liveActivity(s,'breakfast').areaId);
assert.equal(C.normalize({...s,activities:[...s.activities,{id:'meal',name:'old',area:'일상'}]}).activities.some(a=>a.id==='meal'),false);
let cascade=base(),parent=cascade.areas[0].id;
cascade=del(cascade,'area',parent).settings;
assert.equal(C.assignment(cascade,{area:'생활'}).area,null,'legacy area-only clears');
assert.equal(C.historicalAssignment(cascade,C.assignment(cascade,{area:'생활',done:true})).area,'생활');
cascade=del(cascade,'area',cascade.areas[0].id).settings;
assert.equal(cascade.areas.length,0);assert.equal(cascade.activities.length,0);
assert.equal(C.normalize(cascade).areas.length,0,'no reseed');
let moved=base();C.move(moved,'meal','건강');moved=del(moved,'area',moved.areas[0].id).settings;
assert.equal(C.liveActivity(moved,'meal').area,'건강');
assert.equal(C.assignment(moved,{actId:'meal',area:'생활'}).area,'건강');
for(const tagged of [{},{todoId:'t'},{routineId:'r'}]){
  const run={sessionId:'s',actId:'meal',startTs:1000,...tagged};
  assert.throws(()=>del(base(),'activity','meal',{running:run}),/CATALOG_RUNNING/);
  assert.throws(()=>del(base(),'activity','meal',{finalizations:[{running:run}]}),/CATALOG_FINALIZING/);
  assert.doesNotThrow(()=>del(base(),'activity','walk',{running:run}));
}
let concurrent=base(),p=C.preview(concurrent,'area',concurrent.areas[0].id);
concurrent.activities.push({id:'newchild',name:'점심',area:'생활'});
assert.throws(()=>C.deletion(concurrent,p,{operationId:'race'}),/CATALOG_PREVIEW_CHANGED/);
concurrent=base();p=C.preview(concurrent,'activity','meal');concurrent.activities[0].name='아침';
assert.throws(()=>C.deletion(concurrent,p,{operationId:'race'}),/CATALOG_PREVIEW_CHANGED/);
const first=del(base(),'activity','meal');
assert.equal(C.deletion(first.settings,{kind:'activity',id:'meal'},{operationId:first.receipt.id}).replayed,true);
assert.throws(()=>C.mergeHistory(first.settings.catalogHistory,[{...first.receipt,deletedAt:999}]),/CONFLICT/);
assert.equal(C.spanStored({d:day},{sessionId:'s',startTs:1000},601000),true);
assert.equal(C.spanStored({d:day},{sessionId:'s',startTs:1000},601001),false);
assert.equal(C.spanStored({a:{events:[{startTs:1000,endTs:5000,sessionIds:['s']}]},b:{events:[{startTs:5000,endTs:9000,sessionIds:['s']}]}},{sessionId:'s',startTs:1000},9000),true);
assert.equal(C.spanStored({}, {startTs:1000},1000),true);
assert.equal(C.cloudSettings(s).catalogHistory,undefined);
console.log('Catalog lifecycle: deletion, cascade, blank plans, history, recreated IDs, running gates, preview races, replay and finalization passed');
